name: tools
description: Tools for my Flutter apps.
version: 1.0.0

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  quiver: ^3.2.2

dev_dependencies:
  lints: ^6.0.0
